// examples/vue/src/App.vue
<template>
    <div>
        <h1>Terms of Service</h1>

        <!-- The document viewer - SuperDoc renders here -->
        <div ref="documentContainer" class="document-viewer" />

        <!-- Your signature UI - tracked by eSign -->
        <input id="signature-input" type="text" placeholder="Type your full name" :disabled="isAccepted" />

        <!-- Your consent UI - tracked by eSign -->
        <label>
            <input type="checkbox" name="tos" :disabled="!canAccept" />
            I accept the terms of service
        </label>

        <!-- Status display -->
        <div class="status">
            <span v-if="!isReady">Loading...</span>
            <span v-else-if="!requirements.scroll">Please scroll to bottom</span>
            <span v-else-if="!requirements.signature">Please sign</span>
            <span v-else-if="isAccepted">✓ Agreement accepted</span>
        </div>
    </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue';
import SuperDocEsign from '@superdoc-dev/esign';

// Component state
const isReady = ref(false);
const isAccepted = ref(false);
const requirements = ref({
    scroll: false,
    signature: false,
    isValid: false
});

// Template refs
const documentContainer = ref(null);

// Instance ref
let esignInstance = null;

// Computed
const canAccept = computed(() =>
    requirements.value.scroll && requirements.value.signature
);

// Lifecycle
onMounted(() => {
    // Initialize the component
    esignInstance = new SuperDocEsign({
        // 1. Where to render the document
        container: documentContainer.value,

        // 2. What document to show
        document: 'https://storage.googleapis.com/public_statichosting/word_documents/service_agreement.docx',

        // 3. Define requirements
        requirements: {
            scroll: true,
            signature: true,
            consents: ['tos']
        },

        // 4. Tell eSign which UI elements to track
        elements: {
            signature: '#signature-input',
            consents: 'input[name="tos"]'
        },

        // 5. Optional: Populate fields
        fields: {
            userName: 'John Doe',
            date: new Date().toLocaleDateString()
        },

        // 6. Callbacks
        onReady: () => {
            console.log('Component ready');
            isReady.value = true;
        },

        onChange: (status) => {
            console.log('Requirements changed:', status);
            requirements.value = status;

            // Auto-accept when ready
            if (status.isValid && !isAccepted.value) {
                esignInstance.accept();
            }
        },

        onAccept: async (auditData) => {
            console.log('Document accepted:', auditData);

            // Send to your backend
            try {
                await fetch('/api/accept-agreement', {
                    method: 'POST',
                    body: JSON.stringify(auditData)
                });
                isAccepted.value = true;
            } catch (error) {
                console.error('Failed to save:', error);
            }
        },

        onError: (error) => {
            console.error('eSign error:', error);
        }
    });
});

onUnmounted(() => {
    // Cleanup
    esignInstance?.destroy();
});

// Methods you can expose
const resetDocument = () => {
    esignInstance?.reset();
    isAccepted.value = false;
};

const loadNewDocument = (file) => {
    esignInstance?.loadDocument(file);
};
</script>

<style scoped>
.document-viewer {
    height: 500px;
    border: 2px solid #3b82f6;
    border-radius: 8px;
    margin: 20px 0;
    background: white;
    overflow: auto;
}
</style>

// examples/react/src/App.tsx
import React, { useState, useEffect, useRef } from 'react';
import SuperDocEsign from '@superdoc-dev/esign';

/**
 * Basic React integration example
 */
function App() {
    // Component state
    const [isReady, setIsReady] = useState(false);
    const [isAccepted, setIsAccepted] = useState(false);
    const [requirements, setRequirements] = useState({
        scroll: false,
        signature: false,
        isValid: false
    });

    // Ref to hold the eSign instance
    const esignRef = useRef(null);

    useEffect(() => {
        // Initialize the component
        esignRef.current = new SuperDocEsign({
            // 1. Where to render the document
            container: '#document-viewer',

            // 2. What document to show (can be URL, Blob, or File)
            document: 'https://storage.googleapis.com/public_statichosting/word_documents/service_agreement.docx',

            // 3. Define what users must complete
            requirements: {
                scroll: true,      // Must scroll to bottom
                signature: true,   // Must provide signature
                consents: ['tos'] // Must check specific checkboxes
            },

            // 4. Tell eSign which UI elements to track
            elements: {
                signature: '#signature-input',     // Your signature input
                consents: 'input[name="tos"]'     // Your checkbox(es)
            },

            // 5. Optional: Populate fields in the document
            fields: {
                userName: 'John Doe',
                date: new Date().toLocaleDateString()
            },

            // 6. Callbacks for component lifecycle
            onReady: () => {
                console.log('Component ready');
                setIsReady(true);
            },

            onChange: (status) => {
                console.log('Requirements changed:', status);
                setRequirements(status);

                // Auto-accept when all requirements are met
                if (status.isValid && !isAccepted) {
                    esignRef.current.accept();
                }
            },

            onAccept: async (auditData) => {
                console.log('Document accepted with data:', auditData);
                /* 
                auditData contains:
                {
                  timestamp: "2024-01-01T12:00:00Z",
                  duration: 45,  // seconds spent on document
                  scrolled: true,
                  signed: true,
                  consents: ['tos'],
                  fields: { userName: 'John Doe', ... }
                }
                */

                // Send to your backend
                try {
                    await fetch('/api/accept-agreement', {
                        method: 'POST',
                        body: JSON.stringify(auditData)
                    });
                    setIsAccepted(true);
                } catch (error) {
                    console.error('Failed to save acceptance:', error);
                }
            },

            onError: (error) => {
                console.error('eSign error:', error);
            }
        });

        // Cleanup on unmount
        return () => {
            esignRef.current?.destroy();
        };
    }, []);

    // Helper methods you might need
    const resetDocument = () => {
        esignRef.current?.reset();
        setIsAccepted(false);
    };

    const loadNewDocument = (file) => {
        // You can load a new document at any time
        esignRef.current?.loadDocument(file);
    };

    return (
        <div>
            <h1>Terms of Service</h1>

            {/* The document viewer - SuperDoc renders here */}
            <div id="document-viewer" style={{
                height: '500px',
                border: '2px solid #3b82f6',
                borderRadius: '8px',
                margin: '20px 0',
                background: 'white',
                overflow: 'auto'
            }} />

            {/* Your signature UI - tracked by eSign */}
            <input
                id="signature-input"
                type="text"
                placeholder="Type your full name"
                disabled={isAccepted}
            />

            {/* Your consent UI - tracked by eSign */}
            <label>
                <input
                    type="checkbox"
                    name="tos"
                    disabled={!requirements.scroll || !requirements.signature}
                />
                I accept the terms of service
            </label>

            {/* Status display */}
            <div>
                {!isReady && 'Loading...'}
                {isReady && !requirements.scroll && 'Please scroll to bottom'}
                {isReady && !requirements.signature && 'Please sign'}
                {isAccepted && '✓ Agreement accepted'}
            </div>
        </div>
    );
}

export default App;
